version: '3.8'

services:

  postgres:
    env_file:
      - ./.env.production.db
    image: postgres:14.1
    networks:
      - default
    ports:
      - 5432:5432
    expose: 
      - 5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  api:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env.production
    depends_on:
      - postgres
    networks:
      - default
    ports:
      - 8000:8000
      
  migrate:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env.production
    depends_on:
      - db
    networks:
      - default
    command: flask db upgrade
  
  seed:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env.production
    depends_on:
      - migrate
    networks:
      - default
    command: flask seed all

volumes:
  postgres-data: