version: '3'


services:
  app:
    build: .
    networks:
      - default
    ports:
      - 8000:8000
    depends_on:
      - postgres
    env_file:
      - ./.env.production

    

  postgres:
    image: postgres:14.1
    networks:
      - default
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ./.env.production.db



volumes:
  postgres-data:
