"""Add polyline and sportType to track

Revision ID: 45c33166d393
Revises: 08c1b6830fb4
Create Date: 2021-09-27 20:53:02.618647

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '45c33166d393'
down_revision = '08c1b6830fb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    sport_options = sa.Enum(
        'Cycle', 'Run', 'Hike', 'MultiSport', 'Other', name='sportoptions')
    # This will create the enum if it's not already present
    sport_options.create(op.get_bind(), checkfirst=True)

    op.add_column('tracks', sa.Column('polyline', sa.Text(), nullable=False))
    op.add_column('tracks', sa.Column(
        'sport_type', sport_options, nullable=True))
    op.execute("""
        ALTER TABLE users
            ALTER COLUMN primary_sport
                SET DATA TYPE sportoptions
                USING primary_sport::text::sportoptions;
    """)
    primary_sport_options = sa.Enum(name='primarysportoptions')
    primary_sport_options.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    primary_sport_options = sa.Enum(
        'Cycle', 'Run', 'Hike', 'MultiSport', 'Other', name='primarysportoptions')
    # This will create the enum if it's not already present
    primary_sport_options.create(op.get_bind(), checkfirst=True)

    op.drop_column('tracks', 'sport_type')
    op.drop_column('tracks', 'polyline')
    op.execute("""
    ALTER TABLE users
        ALTER COLUMN primary_sport
            SET DATA TYPE primarysportoptions
            USING primary_sport::text::primarysportoptions;
    """)

    sport_options = sa.Enum(name='sportoptions')
    sport_options.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
