"""Add max_elevation column to tracks table

Revision ID: 08c1b6830fb4
Revises: e71b735ce5d6
Create Date: 2021-08-25 16:07:03.115295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08c1b6830fb4'
down_revision = 'e71b735ce5d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column(
        'max_elevation', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'max_elevation')
    # ### end Alembic commands ###
