"""recreate route_id with cascade delete

Revision ID: d51e79953370
Revises: 50ee69d473b3
Create Date: 2021-06-24 16:47:28.407907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd51e79953370'
down_revision = '50ee69d473b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track_points', sa.Column('route_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'track_points', 'routes', ['route_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'track_points', type_='foreignkey')
    op.drop_column('track_points', 'route_id')
    # ### end Alembic commands ###
