"""Update title and img columns on tracks

Revision ID: 40304eeada2c
Revises: 4e6f1dd38515
Create Date: 2022-02-16 15:31:09.091248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40304eeada2c'
down_revision = '4e6f1dd38515'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('map_175px_img_url', sa.String(), nullable=True))
    op.alter_column('tracks', 'title',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.drop_column('tracks', 'map_150px_img_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('map_150px_img_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('tracks', 'title',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('tracks', 'map_175px_img_url')
    # ### end Alembic commands ###
