"""Add img_url to tracks table

Revision ID: 4e6f1dd38515
Revises: 45c33166d393
Create Date: 2022-02-02 10:23:29.226618

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '4e6f1dd38515'
down_revision = '45c33166d393'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column(
        'map_150px_img_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'map_150px_img_url')
    # ### end Alembic commands ###
